In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])

In [5]:
arr=a.reshape(2,3)

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b=np.array([7,8,9,10,11,12])

In [8]:
arr1=b.reshape(2,3)

In [9]:
arr1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
c=np.concatenate((arr,arr1))

In [11]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
d=np.vstack((arr,arr1))

In [13]:
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
d=np.hstack((arr,arr1))

In [16]:
e=np.append(a,[100,200,300])

In [17]:
e

array([  1,   2,   3,   4,   5,   6, 100, 200, 300])

In [18]:
f=np.insert(a,0,[1000,2000,3000])

In [19]:
f

array([1000, 2000, 3000,    1,    2,    3,    4,    5,    6])

In [20]:
g=np.delete(a,[3])

In [21]:
g

array([1, 2, 3, 5, 6])