# numpy basics

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape#shape function

(5,)

In [18]:
arr1=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])

In [19]:
arr1.shape

(2, 2, 5)

In [20]:
print(arr1)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [21]:
arr.dtype

dtype('int32')

In [22]:
arr2=np.array([1.0,2.0,3.0,4.0,5.0])

In [23]:
print(type(arr2))

<class 'numpy.ndarray'>


In [24]:
arr.dtype

dtype('int32')

# to get  a value

In [26]:
arr[0]

1

In [29]:
arr1[0,1]

array([1, 2, 3, 4, 5])

## 

In [31]:
arr2[0]

1.0

In [32]:
arr2[0]=2.0#edit a value 

In [33]:
arr2[0]

2.0

In [38]:
arr1[:,1]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [84]:
oned=np.array([1,2,3,4,5])

In [86]:
oned.ndim


1

In [87]:
twod.ndim

2

In [88]:
oned

array([1, 2, 3, 4, 5])

In [89]:
twod

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [90]:
oned[4]

5

In [91]:
twod[0]

array([1, 2, 3, 4, 5])

In [95]:
twod[1,1]

7

In [93]:
print(twod[1,1]+twod[1,2])

15


In [94]:
twod[0:10:2]

array([[1, 2, 3, 4, 5]])

In [96]:
d=np.array([[1,2,3,4,5,],[6,7,8,9,0]])

In [98]:
print(d[1,1]+d[1,3])

16


In [99]:
d=np.array([[1,2,3,4,5,],[10,20,30,40,50],[100,200,300,400,500]])

In [100]:
d[1:3,0:2]

array([[ 10,  20],
       [100, 200]])