In [2]:
import numpy as n

In [4]:
a=n.empty(5)
print(a)

[0. 0. 0. 0. 0.]


In [8]:
a=n.empty((3,3
          ))
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.33511018e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]


In [9]:
a=n.empty((5,5),dtype=int)
print(a)

[[ 993040408        549         50          0          0]
 [         0          0          0          0         48]
 [1852990827 1697541221  859399481  758592358 1633837413]
 [ 858797101 1633824101 1647141168  943208503  825254194]
 [ 775369830 1952543859  909276021  828454713  926245944]]


In [12]:
a=n.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [14]:
a=n.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
a=n.zeros((5,5),dtype=int) 
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [17]:
a=n.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [18]:
a=n.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
a=n.ones((5,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
