In [3]:
import numpy as np

In [5]:
a=np.eye(5)
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
a=np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a=np.random.rand(10).reshape(5,2)#random number between 1 and 0
a

array([[0.93343834, 0.77899145],
       [0.16644367, 0.37675149],
       [0.81564584, 0.17501484],
       [0.80450164, 0.61165949],
       [0.53891245, 0.97590149]])

In [17]:
a=np.linspace(5,10,10)#finds the number between a limit
a

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [16]:
a=np.random.randn(10).reshape(5,2)#random number between 1 and -1
a

array([[-0.80674929,  0.47674137],
       [-0.60025477, -1.817176  ],
       [ 1.16796956,  1.17247177],
       [-0.50842759, -0.06209684],
       [ 0.2195464 ,  0.86826052]])

In [ ]:
!pip ins